### ISSUE TITLE
[FEATURE REQUEST]全局设置scheme和host参数

### ISSUE THREAD

**Issue by wankey** [didi/DRouter#11]
通常一个app中scheme和host是全局一致的，目前似乎每个目标页面都需要完整设置这些参数，会有大量模版化的代码产生
```kotlin
@Router(scheme = SCHEME, host = HOST, path = PATH)
```
跳转函数也是如此
```kotlin
DRouter.build("$SCHEME://$HOST$PATH").start()
```

建议在DRouter初始化时，增加一个全局Config机制，当没有设置scheme、host时，默认使用全局scheme、host。

参考Retrofit的baseUrl

**Comment by weigao123** [comment]
可以考虑不使用scheme和host？

**Comment by weigao123** [comment]
长时间未回复，暂时关闭，有需要再open
