### ISSUE TITLE
能支持App Bundle吗

### ISSUE THREAD

**Issue by silentpride** [didi/DRouter#13]
8.1起，上架到GP的新应用，都要使用App Bundle的形式。
Arouter打出来的aab，由于动态路由的问题，跳转找不到path。
目前在想办法找解决方案。想问下滴滴的框架现在支持App Bundle吗

**Comment by weigao123** [comment]
这一点我没有测试过，不过国际化团队也在使用drouter并没有报出问题
你可以试一试有问题可以交流

**Comment by weigao123** [comment]
无反馈，暂时关闭
