### ISSUE TITLE
G:\Android\temp\epad\module_oa\build\intermediates\runtime_library_classes_jar\debug\classes.jar: 另一个程序正在使用此文件，进程无法访问。

### ISSUE THREAD

**Issue by lixiangkai1987** [didi/DRouter#14]
G:\Android\temp\epad\module_oa\build\intermediates\runtime_library_classes_jar\debug\classes.jar: 另一个程序正在使用此文件，进程无法访问。

项目接入DRouter之后经常会出现这个，有什么办法解决么？目前我是手动杀掉java.exe

**Comment by holmeszyx** [comment]
+1 ，不知是不是有插件里面有文件操作没有close

可能会导致运行的代码是旧的。

**Comment by weigao123** [comment]
请问用的什么版本，有试过

**Comment by holmeszyx** [comment]
plugin是用的：
`io.github.didi:drouter-plugin-proxy:1.0.1`

lib是:
`io.github.didi:drouter-api:2.0.0`

**Comment by lixiangkai1987** [comment]
刚集成，用的就是目前最新版本

**Comment by ztaober** [comment]
Execution failed for task 'xxx:bundleLibRuntimeDebug'.
> 1 exception was raised by workers:
  java.nio.file.FileSystemException: D:\repo\xxx\android_xxx\xxx\build\intermediates\runtime_library_classes\debug\classes.jar: 另一个程序正在使用此文件，进程无法访问。

**Comment by weigao123** [comment]
看起来只有在windows才有这个问题
是否可以告知下gradle和gradle-wrapper版本，以及这个\build\intermediates\runtime_library_classes\debug\classes.jar包内部的一级包名，需要确认下是否是Android平台类

**Comment by lixiangkai1987** [comment]
classpath "com.android.tools.build:gradle:4.1.1"

https\://services.gradle.org/distributions/gradle-6.5-bin.zip

**Comment by weigao123** [comment]
请用这个版本再试试，关闭了一个jar引用
api 'io.github.didi:drouter-api:2.1.0.0.0.1'

**Comment by ztaober** [comment]
2.1.0.0.0.1版本还是会出现

**Comment by weigao123** [comment]
问一下发生问题的都是windows系统吗

**Comment by holmeszyx** [comment]
> 问一下发生问题的都是windows系统吗

是的。win10

**Comment by lixiangkai1987** [comment]
问一下发生问题的都是windows系统吗

也是Windows

**Comment by weigao123** [comment]
好的感谢反馈，看来集中在windows系统，使用mac的同学不受影响
我这边公司的开发机是mac确实也未复现过，等我找一个windows的机器看看

**Comment by lixiangkai1987** [comment]
> 好的感谢反馈，看来集中在windows系统，使用mac的同学不受影响
> 我这边公司的开发机是mac确实也未复现过，等我找一个windows的机器看看

好的，希望能尽快修复，Windows的话还是挺影响开发，搞两下就要去杀下java.exe

**Comment by lixiangkai1987** [comment]
还没有解决方案么

**Comment by weigao123** [comment]
已解决，可以试一下此版本
api 'io.github.didi:drouter-api:2.1.3'

**Comment by lixiangkai1987** [comment]
> 已解决，可以试一下此版本
> api 'io.github.didi:drouter-api:2.1.3'

好的，感谢，我试下

**Comment by lixiangkai1987** [comment]
> 已解决，可以试一下此版本
> api 'io.github.didi:drouter-api:2.1.3'

我连续试着编译了十遍没有再出现，应该是可以了

**Comment by weigao123** [comment]
> > 已解决，可以试一下此版本
> > api 'io.github.didi:drouter-api:2.1.3'
> 
> 我连续试着编译了十遍没有再出现，应该是可以了

好的谢谢，这个问题我先关闭了，有问题随时交流
