### ISSUE TITLE
似乎无法扫描到打到aar里面的路由服务

### ISSUE THREAD

**Issue by holmeszyx** [didi/DRouter#15]
项目里面分为接口模块`interface`和一个公共服务实现模块`fn`。
本来是都是代码集成的，运行正常。

后面把模块都是打出aar（未传maven仓库），使用`api files`的方式依赖，正常编译过了后，运行发现找不到`@Service`的服务了。（因为测试，只写了一个服务）

对aar依赖大致类似下面的写法：
```gradle

dependencies {

    api files('aar/interface-release.aar')
    api files('aar/fn-release.aar')

}
```

之后，先注释掉上面 `fn`的aar依赖后，把原fn的模块代码拷过来，并调整一下fn模块自己的依赖，将对`interface`模块代码的依赖，改成上面的`interface`的aar。
再编译，运行就是正常的了。

**Comment by crosswall** [comment]
**我也遇到了同样的问题**
我把拦截器写在另一个module中，打成aar后使用maven仓库依赖，transformer似乎并没有对aar文件中的class进行访问，最终生成的路由表里是没有拦截器信息的。 当使用composing builds的方式去构建时transformer是生效的，所以transformer目前只对directory下面的文件生效，不知道是这样设计的还是代码Bug。

**Comment by weigao123** [comment]
> 项目里面分为接口模块`interface`和一个公共服务实现模块`fn`。
> 本来是都是代码集成的，运行正常。
> 
> 后面把模块都是打出aar（未传maven仓库），使用`api files`的方式依赖，正常编译过了后，运行发现找不到`@Service`的服务了。（因为测试，只写了一个服务）
> 
> 对aar依赖大致类似下面的写法：
> 
> ```groovy-gradle
> dependencies {
> 
>     api files('aar/interface-release.aar')
>     api files('aar/fn-release.aar')
> 
> }
> ```
> 
> 之后，先注释掉上面 `fn`的aar依赖后，把原fn的模块代码拷过来，并调整一下fn模块自己的依赖，将对`interface`模块代码的依赖，改成上面的`interface`的aar。
> 再编译，运行就是正常的了。

目前已知如果使用如下的配置，且引用了本地aar的话可能会有问题
android.enableJetifier = true
这个是原生gradle的问题，原生Transform没有正常扫出来该有的aar
可以尝试把这个功能排除指定aar可以解决
android.jetifier.blacklist = fn-release.aar

**Comment by weigao123** [comment]
> **我也遇到了同样的问题**
> 我把拦截器写在另一个module中，打成aar后使用maven仓库依赖，transformer似乎并没有对aar文件中的class进行访问，最终生成的路由表里是没有拦截器信息的。 当使用composing builds的方式去构建时transformer是生效的，所以transformer目前只对directory下面的文件生效，不知道是这样设计的还是代码Bug。

如果是引用本地aar可能会有问题，引用maven库中的aar测试都是没有问题的，是否可以再检查一下
使用最新2.1.0的包，打开debug功能，看一下日志是否有扫描到你的库

apply plugin: 'com.didi.drouter'
drouter {
    debug = true
}

**Comment by crosswall** [comment]
> > **我也遇到了同样的问题**
> > 我把拦截器写在另一个module中，打成aar后使用maven仓库依赖，transformer似乎并没有对aar文件中的class进行访问，最终生成的路由表里是没有拦截器信息的。 当使用composing builds的方式去构建时transformer是生效的，所以transformer目前只对directory下面的文件生效，不知道是这样设计的还是代码Bug。
> 
> 如果是引用本地aar可能会有问题，引用maven库中的aar测试都是没有问题的，是否可以再检查一下
> 使用最新2.1.0的包，打开debug功能，看一下日志是否有扫描到你的库
> 
> apply plugin: 'com.didi.drouter'
> drouter {
> debug = true
> }

更新了版本到2.1.0，debug模式也打开了，一直是maven库依赖，控制台输出log并没有扫描到aar中的@Interceptor注解，于是开始验证猜想AGP版本导致的问题

测试3.4.2，能够输出，能够插入拦截表

测试3.6.1，无法输出，无法插入拦截表

测试4.1.3，无法输出，无法插入拦截表

结论: AGP版本适配问题导致

**Comment by weigao123** [comment]
> > > **我也遇到了同样的问题**
> > > 我把拦截器写在另一个module中，打成aar后使用maven仓库依赖，transformer似乎并没有对aar文件中的class进行访问，最终生成的路由表里是没有拦截器信息的。 当使用composing builds的方式去构建时transformer是生效的，所以transformer目前只对directory下面的文件生效，不知道是这样设计的还是代码Bug。
> > 
> > 
> > 如果是引用本地aar可能会有问题，引用maven库中的aar测试都是没有问题的，是否可以再检查一下
> > 使用最新2.1.0的包，打开debug功能，看一下日志是否有扫描到你的库
> > apply plugin: 'com.didi.drouter'
> > drouter {
> > debug = true
> > }
> 
> 更新了版本到2.1.0，debug模式也打开了，一直是maven库依赖，控制台输出log并没有扫描到aar中的@interceptor注解，于是开始验证猜想AGP版本导致的问题
> 
> 测试3.4.2，能够输出，能够插入拦截表
> 
> 测试3.6.1，无法输出，无法插入拦截表
> 
> 测试4.1.3，无法输出，无法插入拦截表
> 
> 结论: AGP版本适配问题导致
> 
> @weigao123

你这个是mac平台吗

**Comment by holmeszyx** [comment]
更新到: `io.github.didi:drouter-api:2.1.2`。
用之前的测试代码，简单过了下，aar里面的Service可以扫出来了。功能简单测了一下是正常的。

AGP:
`com.android.tools.build:gradle:4.2.2`

**Comment by crosswall** [comment]
可以了

**Comment by weigao123** [comment]
应该是高版本的gradle让aar的磁盘路径正好匹配上了过滤规则，已在2.1.2移除，感谢各位

**Comment by weigao123** [comment]
android.enableJetifier = true
没再复现，跟这个没问题
高版本gradle，扫描出来的jar路径增加了jetified-的前缀
