### ISSUE TITLE
java.lang.IllegalStateException: FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by marekchen** [didi/DRouter#17]
错误堆栈:
2Thread Name: 'main'
3Back traces starts.
4java.lang.IllegalStateException: FragmentManager is already executing transactions
5	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1931)
6	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1967)
7	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:305)
8	at com.didi.drouter.router.ActivityCompat2$HolderFragmentV4.attach(ActivityCompat2.java:121)
9	at com.didi.drouter.router.RouterDispatcher.startActivity(RouterDispatcher.java:62)
10	at com.didi.drouter.router.RouterLoader$1.onContinue(RouterLoader.java:95)
11	at com.didi.drouter.router.RouterDispatcher.start(RouterDispatcher.java:28)
12	at com.didi.drouter.router.ActivityCompat2.startActivityForResult(ActivityCompat2.java:58)
13	at com.didi.drouter.router.InterceptorHandler.handleNext(InterceptorHandler.java:30)
14	at com.didi.drouter.router.InterceptorHandler.handle(InterceptorHandler.java:21)
15	at com.didi.drouter.router.RouterLoader.start(RouterLoader.java:54)
16	at com.didi.drouter.router.RouterLoader.startLocal(RouterLoader.java:79)
17	at com.didi.drouter.router.Request.start(Request.java:58)

发生场景：
外层是viewPager，在其中的一个fragment中使用Drouter.start()，在调用这个方法的同时，切换viewPager。

定位到的源码：
https://github.com/didi/DRouter/blob/6c5dd704729ac20beece8b2bc4083e95c025fda1/drouter-api/src/main/java/com/didi/drouter/router/ActivityCompat2.java#L117-L122

这里一定需要commitNow吗？
有什么方法可以避免这个问题的发生？

**Comment by marekchen** [comment]
如果是在协程中调用 DRouter.start() 需要用withContext(Dispatcher.Main)包一下。

**Comment by weigao123** [comment]
感谢反馈，修复于2.1.1版本
