### ISSUE TITLE
动态下载与api匹配的plugin，无需升级plugin版本，能否自行下载？

### ISSUE THREAD

**Issue by lixiangkai1987** [didi/DRouter#18]
动态下载与api匹配的plugin，无需升级plugin版本，这个能否自行下载，公司的自动构建平台不让联网。

**Comment by weigao123** [comment]
可以用classpath "io.github.didi:drouter-plugin:1.0.8"  代替proxy插件
最新版本关注
https://github.com/didi/DRouter/blob/master/drouter-plugin/build.gradle
