### ISSUE TITLE
支持VirtualApk？

### ISSUE THREAD

**Issue by lixiangkai1987** [didi/DRouter#19]
支持VirtualApk？VirtualApk在 Android10，11用不了了吧，看了项目已经很久没更新了，你们didi内部还在使用这个插件化框架么？

**Comment by weigao123** [comment]
VirtualApk把插件的ClassLoader和宿主的ClassLoader合并在了一起，资源是共享的，所以可以让宿主或者插件通过DRouter无缝引用到对方。
VirtualApk已经适配了9，我理解10和11应该也是可以用的吧
