### ISSUE TITLE
intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK

### ISSUE THREAD

**Issue by oooo7777777** [didi/DRouter#24]
请问下 这样的 intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK

**Comment by oooo7777777** [comment]
如何跳转

**Comment by weigao123** [comment]
DRouter.build("uri")
                        .putExtra(Extend.START_ACTIVITY_FLAGS, Intent.FLAG_ACTIVITY_NEW_TASK)
                        .start(this);

**Comment by oooo7777777** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
