### ISSUE TITLE
请问使用共享元素动画做转场动画，怎么跳转

### ISSUE THREAD

**Issue by oooo7777777** [didi/DRouter#25]
val bundle =
                        ActivityOptionsCompat.makeSceneTransitionAnimation(mContext,
                            Pair(view.findViewById(R.id.ivCover), "ivCover")).toBundle()
                    val intent = Intent(mContext, CourseDetailsActivity::class.java)
                    intent.putExtra("cover", item.cover)
                    intent.putExtra("title", item.name)
                    startActivity(intent, bundle)

**Comment by weigao123** [comment]
使用 Extend.START_ACTIVITY_OPTIONS，把Bundle放到这个参数里

**Comment by weigao123** [comment]
.putExtra(Extend.START_ACTIVITY_OPTIONS, Bundle())

**Comment by wflian** [comment]
这只支持Activity吧？Fragment不支持吧？

**Comment by oooo7777777** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by MarkLDS** [comment]
> 这只支持Activity吧？Fragment不支持吧？

我也遇到了 兄弟这个后面有解决吗
