### ISSUE TITLE
DRouter的onActiviytResult不回调

### ISSUE THREAD

**Issue by lixiangkai1987** [didi/DRouter#26]
最新版本

DRouter.build("didi://router/login")
       .putExtra(key, value)
       .start(this, new RouterCallback.ActivityCallback() {
            @Override
            public void onActivityResult(int resultCode, Intent data) {
            }
       });

使用以上方式的同时也复写了原生Activity的onActivityResult，但是复写的回调了，而DRouter的没有回调，是不能同时共存么？

**Comment by lixiangkai1987** [comment]
2.1.3使用是好的

**Comment by weigao123** [comment]
再试一下 2.2.1版本是否正常了
