### ISSUE TITLE
最新版  2.2.1 经常出现  所有路由无法跳转

### ISSUE THREAD

**Issue by caohao9808** [didi/DRouter#28]
最新版  2.2.1 经常出现  所有路由无法跳转  rebuild 后 重新运行有时候可以解决
primary request "76", router uri "/mine/wallet", need callback "false"
W/DRouterCore: warning: there is no request target match
D/DRouterCore: primary request "76" complete, router uri "/mine/wallet", all reason {}
D/DRouterCore: Request finish

**Comment by holmeszyx** [comment]
有没有用Compose。我这Compose的代码一改动，也是再运行的时候就极大概率报找不到。
然后我把drouter的增量给关了，运行时似乎就没报错了。

`drouter.incremental = false`

**Comment by fushengguoban** [comment]
你好，我也遇到这样的情况，请问是怎么处理的，我已经关闭 drouter.incremental = false 仍然还是同样的错误

**Comment by caohao9808** [comment]
> primary request "76", router uri "/mine/wallet", need callback "false"
> W/DRouterCore: warning: there is no request target match
> D/DRouterCore: primary request "76" complete, router uri "/mine/wallet", all reason {}
> D/DRouterCore: Request finish

我暂时退回使用2.1.2版本，虽然AS运行偶尔报错，但是只要运行起来就不会有这样的问题。

**Comment by weigao123** [comment]
请问是什么运行环境，windows还是mac

**Comment by caohao9808** [comment]
> 

windows

**Comment by weigao123** [comment]
> 你好，我也遇到这样的情况，请问是怎么处理的，我已经关闭 drouter.incremental = false 仍然还是同样的错误

你也是windows吗？

**Comment by weigao123** [comment]
> 最新版 2.2.1 经常出现 所有路由无法跳转 rebuild 后 重新运行有时候可以解决 primary request "76", router uri "/mine/wallet", need callback "false" W/DRouterCore: warning: there is no request target match D/DRouterCore: primary request "76" complete, router uri "/mine/wallet", all reason {} D/DRouterCore: Request finish

修好了，试一下2.2.2版本
