### ISSUE TITLE
不保留活动ActivityCallback失效

### ISSUE THREAD

**Issue by xingquanlu** [didi/DRouter#3]

**Comment by weigao123** [comment]
麻烦详细描述一下问题和复现的步骤，谢谢

**Comment by weigao123** [comment]
> _No description provided._

**Comment by xingquanlu** [comment]
打开开发者不保留活动选项后，点击demo里的“获取ActivityResult，uri=/activity/result”，进入下个页面点“返回结果”，返回后没有预期的Toast“成功获取到ActivityResult”。如果使用官方的onActivityResult是可以收到回调的

**Comment by xingquanlu** [comment]
打开开发者不保留活动选项后，点击demo里的“获取ActivityResult，uri=/activity/result”，进入下个页面点“返回结果”，返回后没有预期的Toast“成功获取到ActivityResult”。如果使用官方的onActivityResult是可以收到回调的

**Comment by weigao123** [comment]
此问题已经开发完成，不过jcenter目前不再提供服务，无法推送新的包，可以先用demo试一下，代码已经提交

**Comment by xingquanlu** [comment]
我看了已经fix了

**Comment by marekchen** [comment]
> 此问题已经开发完成，不过jcenter目前不再提供服务，无法推送新的包，可以先用demo试一下，代码已经提交

你好，新版本可以发mavenCentral吗？

**Comment by weigao123** [comment]
> > 此问题已经开发完成，不过jcenter目前不再提供服务，无法推送新的包，可以先用demo试一下，代码已经提交
> 
> 你好，新版本可以发mavenCentral吗？

maven现在有个问题，发布到maven就必须替换成一个新的groupId，目前没有太好的办法，我先发布下吧
