### ISSUE TITLE
Page是否支持Fragment多层嵌套的呢？

### ISSUE THREAD

**Issue by wflian** [didi/DRouter#34]
DRouter是否可以实现单Activity+多Fragment呢？并且其中Fragment有可能出现多层嵌套的情况

**Comment by weigao123** [comment]
这种暂时还是需要业务层去加载，这部分个性化太高了，很多场景是未知的，比如框架就无法确定Fragment加载到哪个地方，什么形式来展示
所以多层嵌套放到框架里去涵盖所有的情况不太现实

**Comment by weigao123** [comment]
多Fragment现在是支持的，框架可以自动展示，多层嵌套目前很难支持
