### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by kaikaifly** [didi/DRouter#38]
Cause: com/didi/drouter/plugin/RouterTransform has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by ztaober** [comment]
我也遇到过 意思需要使用jdk8来编译
android.enableR8=false +  minifyEnabled true + jdk8  + Drouter插件 = 编译通过
android.enableR8=false +  minifyEnabled true + jdk11  + Drouter插件 = 编译报错
android.enableR8=true +  minifyEnabled true + jdk11  + Drouter插件 = 编译通过

**Comment by weigao123** [comment]
https://github.com/didi/DRouter/issues/31

参考下模板提问哈，我看看你是什么环境发生的
