### ISSUE TITLE
url QueryParameter 未decode的问题

### ISSUE THREAD

**Issue by ztaober** [didi/DRouter#39]
如："didi://web?url=${Uri.encode("https://www.baidu.com?a=b&c=d")}&title=标题"

使用url字段时还需要decode才能使用，和原生url传参使用混淆了
希望框架层QueryParameter解析时就做好decode处理或者支持上层自定义，使用方无需decode

**Comment by weigao123** [comment]
这个点我也是想优化下，但是是这样的，如果不decode，那url字段中的&，和url外部的&就没办法区分了，不能确定是里面的还是外面的，暂时也没想到更好的办法，如果有好办法欢迎指教哈

**Comment by ztaober** [comment]
我看了你的源码com.didi.drouter.utils.getQuery解析时未做decode，
我需要的getQuery效果是下面这种
`
//使用android uri自带解query方法  kv会自动decode
private fun getQuery(uri: Uri): Map<String, String> {
    val queryParameterNames = uri.queryParameterNames
    val map: MutableMap<String, String> = mutableMapOf()
    for (key: String in queryParameterNames) {
        uri.getQueryParameter(key)?.let {
            map[key] = it
        }
    }
    return map
}
`

**Comment by ztaober** [comment]
对于url传参的kv，不管有没有encode过，默认做一次decode操作，业务方就直接使用即可

**Comment by weigao123** [comment]
哦不好意思，我理解错了，我看做是希望增加一个自动编码的策略
你的诉求和方案都是合理的，我改一下，周一提供一个2.2.2版本的包哈
感谢反馈

**Comment by weigao123** [comment]
已发布2.3.1
