### ISSUE TITLE
关于drouter-plugin-proxy

### ISSUE THREAD

**Issue by CCtomorrow** [didi/DRouter#4]
为什么要做一个gradle plugin的proxy，然后里面也只是下载了真正的gradle plugin，然后去执行逻辑，是出于什么考虑，很好奇。

**Comment by weigao123** [comment]
首先DRouter的API和Gradle插件版本有依赖关系。
像滴滴出行这种大型app，涉及业务线繁多，集成时有一个集成壳工程，整体看是一个典型的总分总的架构，分代表的是各个业务线，最底层基于一个通用的中台组件。
而开发阶段各业务线利用自己团队的壳工程+自己的业务代码+通用中台组件独立进行编译调试，一旦中台组件升级了DRouter的API版本，每个业务线就都需要手动更新自己的壳工程的DRouter Gradle插件版本，否则大概率就会编译失败。
为了解决这个问题，所以开发了代理插件，各业务线无需再关心中台因DRouter新增了功能而更新了API版本，代理会自动下载最新的插件，也就不会再引起编译失败，大大提升了体验和效率。
