### ISSUE TITLE
run 的时候偶现报错

### ISSUE THREAD

**Issue by zqlq4ever** [didi/DRouter#40]
【平台环境】：windows
【Android Studio版本】：chipmunk| 2021.2.1 Patch 1
【编译使用Java版本】：jdk11
【kotlin版本】： id 'org.jetbrains.kotlin.android' version '1.7.0-RC2' apply false
【gradle-plugin版本】：https\://services.gradle.org/distributions/gradle-7.3.3-bin.zip
【gradle-wrapper版本】：gradle-7.3.3-bin.zip
【drouter版本】：drouter-api:2.2.1
【复现步骤】：run 的时候会偶现
【期望结果】：正常运行app
【日志】：
<img width="1858" alt="051a26b7612759c9921df74bda4f11d" src="https://user-images.githubusercontent.com/37474811/172359884-4c1d8c5a-e954-433a-a909-e5792889ef84.png">

**Comment by weigao123** [comment]
看起来和incremental有关，试一下增加这个配置看看

apply plugin: 'com.didi.drouter'
drouter {
    incremental = false
}
