### ISSUE TITLE
Google Play新上架提交aab文件，无法跳转

### ISSUE THREAD

**Issue by oooo7777777** [didi/DRouter#44]
我们的项目使用了DRouter，并且版本依赖已升级至2.1.3，编译生成出来的aab文件，安装到手机上，无法正常跳转。报 warning: there is no request target match
编译出来的apk能正常使用~
请问是否有解决办法，往告知，谢谢。

**Comment by oooo7777777** [comment]
编译成apk能正常跳转

**Comment by oooo7777777** [comment]
[LoadProvider] onCreate and DRouter set application | com.merit.common.MyApplication@1dc
DRouter start load router table in drouter-table-thread
[===DRouter load complete=== waste time: 6ms]
Request start -------------------------------------------------------------
primary request "0", router uri "LoginActivity", need callback "false"
request "0" find target class "LoginActivity", type "1", priority "0"
>> Enter request "0" all interceptors
<< Pass request "0" all interceptors
request "0", class "null" start execute
==== request "0" complete, reason "complete" ====
primary request "0" complete, router uri "LoginActivity", all reason {0=complete}
Request finish ------------------------------------------------------------

**Comment by oooo7777777** [comment]
以下为apk打印日志

**Comment by oooo7777777** [comment]
以下为Apk打印日志
[LoadProvider] onCreate and DRouter set application | com.merit.common.MyApplication@1dc
DRouter start load router table in drouter-table-thread
[===DRouter load complete=== waste time: 6ms]
Request start -------------------------------------------------------------
primary request "0", router uri "LoginActivity", need callback "false"
request "0" find target class "LoginActivity", type "1", priority "0"
>> Enter request "0" all interceptors
<< Pass request "0" all interceptors
request "0", class "null" start execute
==== request "0" complete, reason "complete" ====
primary request "0" complete, router uri "LoginActivity", all reason {0=complete}
Request finish ------------------------------------------------------------

**Comment by oooo7777777** [comment]
以下为aab打印日志
DRouter start load router table in drouter-table-thread
[===DRouter load complete=== waste time: 2ms]
Request start -------------------------------------------------------------
primary request "0", router uri "LoginActivity", need callback "false"
warning: there is no request target match
primary request "0" complete, router uri "LoginActivity", all reason {}
Request finish ------------------------------------------------------------

**Comment by LuoboDcom** [comment]
解决了吗？

**Comment by weigao123** [comment]
误报，是业务方没有把正常的业务模块依赖进来的原因
