### ISSUE TITLE
如何获取路由中携带的参数

### ISSUE THREAD

**Issue by pengdaqian2020** [didi/DRouter#48]
```
DRouter.build("xxx://xxxx/xxxx")
      .putExtra("cid", "xxxx")
      .putExtra("type", "xxxx")
      .start()
```

然后在对应的activity里面
```
val request = RouterHelper.getRequest(this)
if(request != null) {
    type = request.getExtra().getInt("type")
}
```

request总是为null，无法取到路由请求里面携带的参数

如果要获取路由参数，需要自己封装方法从intent里面取吗？

**Comment by weigao123** [comment]
对，是的，需要从intent里获取到
RouterHelper.getRequest(this)的使用场景是异步路由
https://github.com/didi/DRouter/wiki/1.-Router#%E5%BC%82%E6%AD%A5activity
