### ISSUE TITLE
 有些lifecycle版本要求lifecyle.addObserver需要在主线程中调用

### ISSUE THREAD

**Issue by x930073498** [didi/DRouter#5]
![image](https://user-images.githubusercontent.com/16031755/114141300-01aef080-9944-11eb-925a-6fb509be8cc0.png)
![image](https://user-images.githubusercontent.com/16031755/114141366-15f2ed80-9944-11eb-8f6f-483496570cb5.png)
![image](https://user-images.githubusercontent.com/16031755/114141444-2acf8100-9944-11eb-83d5-017679c771e7.png)
![image](https://user-images.githubusercontent.com/16031755/114141483-358a1600-9944-11eb-8ddc-46c7f1577f69.png)

**Comment by weigao123** [comment]
你好，能具体再描述下需要drouter做什么吗，我是否可以理解为，这种情况只能是使用方在主线程调用？

**Comment by x930073498** [comment]
我看DRouter中在有些绑定lifecycle的方法中加了synchronized，那就认为该方法是可以多线程使用的，如下图所示方法，会导致使用者误用出错。同时fragment的创建有的版本也需要在主线程，私以为要么强切到主线程，要么在方法上标识主线程，或者您使用其他方法去改变行为，减少使用者的误用。
![image](https://user-images.githubusercontent.com/16031755/115170640-a921e500-a0f3-11eb-808a-659fb80c38e5.png)

**Comment by weigao123** [comment]
感谢反馈，最近会发一个版本，把这个位置的注解增加主线程注解

**Comment by weigao123** [comment]
已增加注解@MainThread
请使用

**Comment by weigao123** [comment]
请问一下你用的lifecycle是哪个版本，我看了较新的 api 'androidx.lifecycle:lifecycle-runtime:2.2.0' 没有发现要求比较主线程

**Comment by x930073498** [comment]
> 请问一下你用的lifecycle是哪个版本，我看了较新的 api 'androidx.lifecycle:lifecycle-runtime:2.2.0' 没有发现要求比较主线程

我记得很多版本有，我现在用2.3.1，也有要求。
![image](https://user-images.githubusercontent.com/16031755/133018830-e0523bd4-a9a9-4dcd-b3be-73b482e62485.png)
