### ISSUE TITLE
动态模块可以用吗？

### ISSUE THREAD

**Issue by githubliruiyuan** [didi/DRouter#55]
Dynamic-feature module 使用不了service

DRouterCore: [Local] Get service "xxx" fail with default "null"

**Comment by weigao123** [comment]
可以使用，按照下面的方法先自查下

1、首先确认下这些类是不是在apk里
可以把debug的apk拖到AndroidStudio里看看有没有这个类
遇到找不到目标的问题可能只是因为没有把module引入进来
api project(':xxx')

2、打开编译期日志
apply plugin: 'com.didi.drouter'
drouter {
debug = true
}
查看编译期是否有问题，可以看到路由表，可以看到哪些类用到了DRouter

3、看一下插件生成的类是否正常
目录在
app/build/intermediates/transforms/DRouter/debug/xx/com/didi/drouter/loader

4、运行期日志
Logcat中抓取 DRouterCore 关键字

5、接入方法参见wiki
https://github.com/didi/DRouter/wiki
