### ISSUE TITLE
页面路由动画

### ISSUE THREAD

**Issue by wflian** [didi/DRouter#59]
Activity、Fragment的页面跳转路由动画要如何配置

**Comment by weigao123** [comment]
DRouter.build("didi://router/message")
       .putExtra(Extend.START_ACTIVITY_FLAGS, Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK)   // flag
       .putExtra(key, value)  // 自定义参数
       .start(context, new RouterCallback() {
            @Override
            public void onResult(@NonNull Result result) {
 
            }
       });

可以放到自定义参数里，Extend里面有定义动画Key

**Comment by wflian** [comment]
不是转场动画，就是普通的页面切换动画

**Comment by wflian** [comment]
DRouter.build("/activity/Test1_Value1_Value2?Arg3=Value3")
            .putExtra(Extend.START_ACTIVITY_ANIMATION, new int[]  { R.anim.fade_out, R.anim.fade_in  })
            .putExtra("Arg4", "Value4")
            .start(this);

**Comment by weigao123** [comment]
内部的实现是
        int[] anim = request.getIntArray(Extend.START_ACTIVITY_ANIMATION);
        if (context instanceof Activity && anim != null && anim.length == 2) {
            ((Activity) context).overridePendingTransition(anim[0], anim[1]);
        }
你想要的实现是什么？
