### ISSUE TITLE
拦截器能否通过路由方式获得？

### ISSUE THREAD

**Issue by x930073498** [didi/DRouter#6]
项目中多个模块业务分离，其他模块不太好使用硬代码将其他模块中拦截器引入，比如用户模块中有登录拦截器，其他模块中无法使用该拦截器class，可有更好的办法，现在可使用handler实现，可总觉得很怪。

**Comment by weigao123** [comment]
了解了，我评估下，再下一个版本中支持

**Comment by weigao123** [comment]
功能已开发完成，版本1.0.6

**Comment by x930073498** [comment]
大佬辛苦了
