### ISSUE TITLE
发现一个小问题

### ISSUE THREAD

**Issue by WANZIzZ** [didi/DRouter#7]
从FragmentA跳入ActivityB，在ActivityB中setResult后，FragmentA中会有回调。
从FragmentA跳入ActivityB，再从ActivityB跳转（start(Context context, RouterCallback callback)）到ActivityC，销毁ActivityC后，在ActivityB中setResult，FragmentA中无法收到回调。如果ActivityB跳转ActivityC时使用的是start()，FragmentA中会有回调。

**Comment by WANZIzZ** [comment]
> 从FragmentA跳入ActivityB，在ActivityB中setResult后，FragmentA中会有回调。
> 从FragmentA跳入ActivityB，再从ActivityB跳转（start(Context context, RouterCallback callback)）到ActivityC，销毁ActivityC后，在ActivityB中setResult，FragmentA中无法收到回调。如果ActivityB跳转ActivityC时使用的是start()，FragmentA中会有回调。

补充下，这里的 start(Context context, RouterCallback callback) 都是 RouterCallback.ActivityCallback

**Comment by weigao123** [comment]
你好，我按你说的操作试了一下，是可以正常接收到结果的，请问你这边还能复现这个问题吗？

**Comment by WANZIzZ** [comment]
> 你好，我按你说的操作试了一下，是可以正常接收到结果的，请问你这边还能复现这个问题吗？

我这边的版本是 1.0.4 ，不知道你们是不是已经修复过了

**Comment by weigao123** [comment]
已更新版本，可以再试一下，如有问题随时交流，感谢

**Comment by WANZIzZ** [comment]
> 已更新版本1.0.6，可以再试一下，如有问题随时交流，感谢

新版本的没这个问题了，谢谢啦
